/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPettyCashWalletsRouteImport } from './routes/_authenticated/petty-cash-wallets'
import { Route as AuthenticatedPaymentRequestsRouteImport } from './routes/_authenticated/payment-requests'
import { Route as AuthenticatedMyPettyCashRouteImport } from './routes/_authenticated/my-petty-cash'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDieselRouteImport } from './routes/_authenticated/diesel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedPettyCashWalletsUserIdRouteImport } from './routes/_authenticated/petty-cash-wallets.$userId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPettyCashWalletsRoute =
  AuthenticatedPettyCashWalletsRouteImport.update({
    id: '/petty-cash-wallets',
    path: '/petty-cash-wallets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentRequestsRoute =
  AuthenticatedPaymentRequestsRouteImport.update({
    id: '/payment-requests',
    path: '/payment-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyPettyCashRoute =
  AuthenticatedMyPettyCashRouteImport.update({
    id: '/my-petty-cash',
    path: '/my-petty-cash',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDieselRoute = AuthenticatedDieselRouteImport.update({
  id: '/diesel',
  path: '/diesel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPettyCashWalletsUserIdRoute =
  AuthenticatedPettyCashWalletsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedPettyCashWalletsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diesel': typeof AuthenticatedDieselRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-petty-cash': typeof AuthenticatedMyPettyCashRoute
  '/payment-requests': typeof AuthenticatedPaymentRequestsRoute
  '/petty-cash-wallets': typeof AuthenticatedPettyCashWalletsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/petty-cash-wallets/$userId': typeof AuthenticatedPettyCashWalletsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diesel': typeof AuthenticatedDieselRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-petty-cash': typeof AuthenticatedMyPettyCashRoute
  '/payment-requests': typeof AuthenticatedPaymentRequestsRoute
  '/petty-cash-wallets': typeof AuthenticatedPettyCashWalletsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/petty-cash-wallets/$userId': typeof AuthenticatedPettyCashWalletsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diesel': typeof AuthenticatedDieselRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/my-petty-cash': typeof AuthenticatedMyPettyCashRoute
  '/_authenticated/payment-requests': typeof AuthenticatedPaymentRequestsRoute
  '/_authenticated/petty-cash-wallets': typeof AuthenticatedPettyCashWalletsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/petty-cash-wallets/$userId': typeof AuthenticatedPettyCashWalletsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit-logs'
    | '/dashboard'
    | '/diesel'
    | '/inventory'
    | '/my-petty-cash'
    | '/payment-requests'
    | '/petty-cash-wallets'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/users'
    | '/petty-cash-wallets/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit-logs'
    | '/dashboard'
    | '/diesel'
    | '/inventory'
    | '/my-petty-cash'
    | '/payment-requests'
    | '/petty-cash-wallets'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/users'
    | '/petty-cash-wallets/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/diesel'
    | '/_authenticated/inventory'
    | '/_authenticated/my-petty-cash'
    | '/_authenticated/payment-requests'
    | '/_authenticated/petty-cash-wallets'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/petty-cash-wallets/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/petty-cash-wallets': {
      id: '/_authenticated/petty-cash-wallets'
      path: '/petty-cash-wallets'
      fullPath: '/petty-cash-wallets'
      preLoaderRoute: typeof AuthenticatedPettyCashWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-requests': {
      id: '/_authenticated/payment-requests'
      path: '/payment-requests'
      fullPath: '/payment-requests'
      preLoaderRoute: typeof AuthenticatedPaymentRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-petty-cash': {
      id: '/_authenticated/my-petty-cash'
      path: '/my-petty-cash'
      fullPath: '/my-petty-cash'
      preLoaderRoute: typeof AuthenticatedMyPettyCashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diesel': {
      id: '/_authenticated/diesel'
      path: '/diesel'
      fullPath: '/diesel'
      preLoaderRoute: typeof AuthenticatedDieselRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/petty-cash-wallets/$userId': {
      id: '/_authenticated/petty-cash-wallets/$userId'
      path: '/$userId'
      fullPath: '/petty-cash-wallets/$userId'
      preLoaderRoute: typeof AuthenticatedPettyCashWalletsUserIdRouteImport
      parentRoute: typeof AuthenticatedPettyCashWalletsRoute
    }
  }
}

interface AuthenticatedPettyCashWalletsRouteChildren {
  AuthenticatedPettyCashWalletsUserIdRoute: typeof AuthenticatedPettyCashWalletsUserIdRoute
}

const AuthenticatedPettyCashWalletsRouteChildren: AuthenticatedPettyCashWalletsRouteChildren =
  {
    AuthenticatedPettyCashWalletsUserIdRoute:
      AuthenticatedPettyCashWalletsUserIdRoute,
  }

const AuthenticatedPettyCashWalletsRouteWithChildren =
  AuthenticatedPettyCashWalletsRoute._addFileChildren(
    AuthenticatedPettyCashWalletsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDieselRoute: typeof AuthenticatedDieselRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMyPettyCashRoute: typeof AuthenticatedMyPettyCashRoute
  AuthenticatedPaymentRequestsRoute: typeof AuthenticatedPaymentRequestsRoute
  AuthenticatedPettyCashWalletsRoute: typeof AuthenticatedPettyCashWalletsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDieselRoute: AuthenticatedDieselRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMyPettyCashRoute: AuthenticatedMyPettyCashRoute,
  AuthenticatedPaymentRequestsRoute: AuthenticatedPaymentRequestsRoute,
  AuthenticatedPettyCashWalletsRoute:
    AuthenticatedPettyCashWalletsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
